### ISSUE TITLE
Обработчик данных вебхука

### ISSUE THREAD

**Issue by max-arnold** [dnagikh/pyprodamus#1]
Добавьте пожалуйста парсер данных вебхука: https://help.prodamus.ru/payform/integracii/rest-api/instrukcii-dlya-samostoyatelnaya-integracii-servisov#kak-prinyat-uvedomlenie-ob-uspeshnoi-oplate

**Comment by dnagikh** [comment]
@max-arnold после непродолжительных попыток распарсить реквест от продамус, было решено делать быстро и лоб, вручную формируя свой словарь данных на основе request.post(). Могу опубликовать его, но это крайне плохая реализация.

На текущий момент доступа к Продамус нет, мне бы исходный реквест от него в любом формате, я бы переписал функцию на парсер.

**Comment by max-arnold** [comment]
Отправил вам подробности почтой

**Comment by dnagikh** [comment]
Спасибо, @max-arnold 
Обновил репозиторий

**Comment by max-arnold** [comment]
Там в коде print отладочный затесался

**Comment by max-arnold** [comment]
Ещё имя модуля в README и setup.py содержит `-` что невалидно, требуются пляски с бубном:

```
Python 3.11.5 (main, Aug 25 2023, 01:57:11) [Clang 14.0.3 (clang-1403.0.22.14.1)]
Type 'copyright', 'credits' or 'license' for more information
IPython 8.15.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import python-prodamus
  Cell In[1], line 1
    import python-prodamus
                 ^
SyntaxError: invalid syntax


In [2]: import python_prodamus
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Cell In[2], line 1
----> 1 import python_prodamus

ModuleNotFoundError: No module named 'python_prodamus'

In [3]: import importlib

In [4]: python_prodamus = importlib.import_module("python-prodamus.extension")

In [5]: python_prodamus.PyProdamus
Out[5]: python-prodamus.extension.PyProdamus
```

**Comment by dnagikh** [comment]
@max-arnold 
Спасибо! Перезагрузил пакет на pypi без лишних символов. Наверное, нужно было обновить версию, но поторопился, снес репо. Пришлось создать с новым именем.
